version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-107-109.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: da3e5balvsn1em
            ssl: true
            user: ipodgwlyiofcsc
            password: 355c929b0400039157c53de87b07bbea181cd6920eb5e28480dd74e97f75af81
            migrations: true

